name: Kotlin Ropa Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up Android SDK
      uses: reactivecircus/android-setup-action@v2
      with:
        sdk-version: '34' 

    - name: Build and test
      run: |
        ./gradlew test
